apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-inference
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anti4ris98/Mlops-project.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: aiops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
